apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocpp-lab.fullname" . }}
  labels: {{- include "ocpp-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "ocpp-lab.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
